service: money-tracker-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  get-categories:
    handler: src/main.getCategories
    events:
      - httpApi:
          path: /v1/categories
          method: GET

  create-category:
    handler: src/main.createCategory
    events:
      - httpApi:
          path: /v1/categories
          method: POST

  get-subcategories:
    handler: src/main.getSubcategories
    events:
      - httpApi:
          path: /v1/subcategories
          method: GET

  get-movement-types:
    handler: src/main.getMovementTypes
    events:
      - httpApi:
          path: /v1/movement-types
          method: GET
